"""Whole-robot bill of materials by subsystem -> docs/BOM_OVERVIEW.md + docs/bom_overview.csv.

Inputs (both tracked, both generated by their own tools):
  amr/bom_amr.csv  - own AMR base rev B4: structure, drives, power, safety, dock, arm and coffee power, Jetson
  docs/bom.csv     - superstructure (arms, vision, face, coffee backpack, shells, custom parts, fasteners), made for
                     the earlier Ranger Mini variant
Rows of docs/bom.csv that the own AMR replaces (the Ranger Mini base itself, its power pack, safety chain, wiring and
dock, the adapter plate and battery/scanner brackets, the deck cover) are left out and listed at the end, so nothing is
counted twice. Component costs only, EUR excl. VAT, quantity 1 (prototype). No labour, no margin.

Run: python scripts/bom_overview.py
"""
import csv
import re
from collections import OrderedDict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GROUPS = ["Base AMR (structure, drives, castors, covers)", "Safety", "Power", "Dock", "Arms & hands",
          "Vision & compute", "Structure & shells", "Coffee module"]

# AMR ids -> group (prefix match, first hit wins); anything else in group "base" is Base AMR
AMR_RULES = [
    (("S01_", "S02_", "E02_", "E41_", "SE1_", "HL1_", "E21_", "E20_SC1", "E2H_", "E2I_", "E2M_", "E2C_", "E2D_",
      "RB1-10", "E2J_", "SCT_", "E59_"), "Safety"),
    (("E01_robopad", "E35_", "E37_"), "Dock"),
    (("B01_", "G01_", "E38b", "E03_", "E10_", "E11_", "E12_", "E17_", "E18_", "E31_", "E33_", "E2F_", "E13_", "E14_",
      "E15_", "E2G_", "E16_", "E30_", "E34_", "E19_", "E27_", "E32_", "E2K_", "D0_", "E58_", "H01", "E0x_", "E0C_",
      "E5A_"), "Power"),
    (("E36_", "E25_"), "Vision & compute"),
]
AMR_GROUP = {"dock": "Dock", "arm_OA": "Arms & hands", "barista": "Coffee module", "superstructure": "Vision & compute"}

# docs/bom.csv: sections kept and where they go; None = replaced by the own AMR
DOC_SECTION = {"A": None, "B": "Arms & hands", "C": "Vision & compute", "D": "Vision & compute", "E": "Coffee module",
               "F": None, "G": None, "H": None, "I": "Structure & shells", "J": None, "K": "Structure & shells",
               "L": "Structure & shells"}
DOC_DROP_ITEMS = ("NVIDIA Jetson Orin NX 16 GB module",   # replaced by the AMR's E51 reComputer J4012
                  "3.3 V CAN transceiver",                 # was for the own-pack BMS; AMR uses Discover LYNK + E36
                  "Industrial Ethernet switch",            # replaced by the AMR's E25
                  "P01_", "P03_", "P04_", "P05_", "P06_", "P07_", "P08_", "P09_", "P11_",  # Ranger adapter/brackets
                  "SH01_")                                  # deck cover -> AMR covers K01-K06
COFFEE_PARTS = ("P21_", "P22_", "P23_", "P24_", "P25_", "P26_", "P30_", "P31_", "SH06_")


def url_of(s):
    m = re.search(r"https?://[^\s,;)]+", s or "")
    return m.group(0) if m else ""


def short(s, n=70):
    s = " ".join((s or "").split())
    return s if len(s) <= n else s[: n - 1] + "…"


def status_amr(tag):
    t = tag.upper()
    if t in ("SOURCED", "SECONDARY"):
        return "documented"
    if t == "QUOTE":
        return "quote needed"
    return "estimate, quote needed"


def status_doc(src):
    if url_of(src):
        return "documented"
    if "process cost model" in src:
        return "estimate, shop quote needed"
    return "estimate, quote needed"


rows, dropped = [], []
for r in csv.DictReader(open(ROOT / "amr/bom_amr.csv", newline="")):
    if r["in_total"] != "Y" or r["id"].startswith(("SUBTOTAL", "TOTAL")):
        continue
    g = AMR_GROUP.get(r["group"])
    if g is None:
        g = next((grp for pre, grp in AMR_RULES if r["id"].startswith(pre)), GROUPS[0])
    q = float(r["qty"] or 1)
    u = float(r["unit_eur_at1"])
    rows.append(dict(group=g, item=f'{r["id"].split("_")[0]} {r["part"]}', pn=r["process_mpn"], qty=q, unit=u,
                     total=q * u, source=url_of(r["source"]) or r["supplier"] or r["source"],
                     status=status_amr(r["price_tag"]), origin="amr/bom_amr.csv"))
for r in csv.DictReader(open(ROOT / "docs/bom.csv", newline="")):
    sec = r["section"][:1]
    if sec not in DOC_SECTION:
        continue
    g = DOC_SECTION[sec]
    item = r["item"]
    if g is None or item.startswith(DOC_DROP_ITEMS) or any(item.startswith(d) for d in DOC_DROP_ITEMS):
        dropped.append((r["section"], item, float(r["total_eur"] or 0)))
        continue
    if item.startswith(COFFEE_PARTS):
        g = "Coffee module"
    q = float(r["qty"] or 1)
    u = float(r["unit_eur"] or 0)
    if u == 0:
        continue                                    # consumables / included items (listed in docs/BOM.md)
    rows.append(dict(group=g, item=item, pn=r["mpn"], qty=q, unit=u, total=q * u,
                     source=url_of(r["source"]) or r["source"], status=status_doc(r["source"]), origin="docs/bom.csv"))

by = OrderedDict((g, [x for x in rows if x["group"] == g]) for g in GROUPS)
tot = sum(x["total"] for x in rows)
doc_eur = sum(x["total"] for x in rows if x["status"] == "documented")


def eur(v):
    return f"{v:,.0f}"


L = ["# Giorgio: bill of materials by subsystem",
     "",
     "> Generated by `python scripts/bom_overview.py` from `amr/bom_amr.csv` (own AMR base rev B4) and `docs/bom.csv`",
     "> (superstructure). **Component costs only**: EUR excluding VAT, quantity 1 (prototype), no labour and no margin.",
     "> Status *documented* = a public price or a manufacturer/distributor document; *quote needed* = the price is an",
     "> estimate or is behind a login and must be confirmed by a quote. Nothing has been bought yet.",
     "",
     "## Totals",
     "",
     "| Subsystem | Rows | Documented | Quote needed | Subtotal (EUR) |",
     "|---|---:|---:|---:|---:|"]
for g, xs in by.items():
    d = sum(1 for x in xs if x["status"] == "documented")
    L.append(f"| [{g}](#{re.sub(r'[^a-z0-9 -]', '', g.lower()).replace(' ', '-')}) | {len(xs)} | {d} | {len(xs) - d} | "
             f"{eur(sum(x['total'] for x in xs))} |")
L += [f"| **Total, barista configuration** | **{len(rows)}** | **{sum(1 for x in rows if x['status'] == 'documented')}** | "
      f"**{sum(1 for x in rows if x['status'] != 'documented')}** | **{eur(tot)}** |",
      "",
      f"{eur(doc_eur)} EUR ({doc_eur / tot:.0%}) of the total comes from documented prices; the rest is estimates "
      "waiting for quotes. Volume prices (at 10 and 50 units) for the base are in `amr/bom_amr.csv`.",
      "",
      "Not included: options (certified-arm extras `arm_C48`, the larger NPB-1700 dock charger, ORCA Hand / AmazingHand "
      "instead of the OpenArm grippers, see [FEASIBILITY.md](../FEASIBILITY.md)), consumables (cups, capsules), labour "
      "and certification costs (see [amr/INDUSTRIALIZATION.md](../amr/INDUSTRIALIZATION.md)).",
      ""]
for g, xs in by.items():
    L += [f"## {g}", "", "| Item | Part number | Qty | Unit (EUR) | Source | Status |", "|---|---|---:|---:|---|---|"]
    for x in sorted(xs, key=lambda x: -x["total"]):
        src = x["source"]
        src_md = f"[link]({src})" if src.startswith("http") else short(src, 50).replace("|", "/")
        qty = f"{x['qty']:g}"
        L.append(f"| {short(x['item'], 80).replace('|', '/')} | {short(x['pn'], 50).replace('|', '/')} | {qty} | "
                 f"{x['unit']:,.2f} | {src_md} | {x['status']} |")
    L += [f"| **Subtotal** | | | **{eur(sum(x['total'] for x in xs))}** | | |", ""]
L += ["## Rows of docs/bom.csv left out (replaced by the own AMR base)", "",
      "These belong to the earlier AgileX Ranger Mini variant. Their function is now inside the base "
      "(`amr/bom_amr.csv`).", "", "| Section | Item | EUR |", "|---|---|---:|"]
for s, i, v in dropped:
    L.append(f"| {s} | {short(i, 90).replace('|', '/')} | {eur(v)} |")
L.append("")
(ROOT / "docs/BOM_OVERVIEW.md").write_text("\n".join(L))
with open(ROOT / "docs/bom_overview.csv", "w", newline="") as f:
    w = csv.DictWriter(f, fieldnames=["group", "item", "pn", "qty", "unit", "total", "source", "status", "origin"])
    w.writeheader()
    for g, xs in by.items():
        w.writerows(xs)
print(f"{len(rows)} rows, total EUR {tot:,.0f}; " + "; ".join(f"{g}: {sum(x['total'] for x in xs):,.0f}"
                                                         for g, xs in by.items()))
