#!/usr/bin/env python3
"""Generate product-variant netlists from netlist.yaml and check them.

  netlist.yaml          prototype / demo build on AgileX Tracer 2.0 (default)
  netlist_mir250.yaml   sellable product on MiR250 (cad/BASE_DECISION.md section 4)

Usage: python3 variants.py      -> writes netlist_mir250.yaml and CHECKS_MIR250.md
"""
import copy
import subprocess
import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
base = yaml.safe_load((HERE / "netlist.yaml").read_text())
n = copy.deepcopy(base)

n["meta"]["revision"] = base["meta"]["revision"] + " / variant MiR250"
n["meta"]["variant"] = "MiR250 product base"
n["sources"]["mir250"] = "https://mobile-industrial-robots.com/products/robots/mir250/specifications"
n["sources"]["base_decision"] = "cad/BASE_DECISION.md"

# --- base: MiR250 has its own Li-ion battery and charger; nothing of ours feeds traction
n.pop("tracer", None)
drop_loads = {"TRACER_CHG_IN", "TRACER_DRIVE", "TRACER_ELEC", "SCAN_F", "SCAN_R"}
n["loads"] = [l for l in n["loads"] if l["id"] not in drop_loads]
n["buses"] = [b for b in n["buses"] if b["id"] != "T24"]
n["branches"] = [b for b in n["branches"] if b["id"] not in ("W08", "W09")]
for b in n["branches"]:
    if b["id"] == "W01":
        b["current"]["branches"] = [x for x in b["current"]["branches"] if x != "W08"]
    if b["id"] == "W10":
        b["desc"] = "S24 -> F20 -> PNOZ + coils + MiR interface relays (distribution)"
n["fuses"] = [f for f in n["fuses"] if f["id"] not in ("F5", "F7")]
n["exclusive"] = []
for c in n["components"]:
    if c["id"] in ("CHG_TRACER", "SCANNER", "CAN_ISO", "TRACER"):
        c["qty"] = 0
        c["note"] = "removed in the MiR250 variant (base supplies it or it is not needed)"
    if c["id"] == "FUSE_SPF015":
        c["qty"] = 0
    if c["id"] == "FUSE_SPF012":
        c["qty"] = 1
n["components"].append({"id": "MIR250", "short": "MiR250", "category": "load", "qty": 1, "manufacturer": "Mobile Industrial Robots",
                        "mpn": "MiR250 (2x nanoScan3, 12 safety functions ISO 13849-1, 1 auxiliary E-stop input, 4 DI / 4 DO)",
                        "price_eur": 0, "source": "mir250"})
n["components"].append({"id": "MIR_IF", "short": "", "category": "safety", "qty": 1, "manufacturer": "Pilz / Phoenix",
                        "mpn": "interface: PNOZ m EF 4DI4DOR contacts -> MiR auxiliary E-stop input; MiR status DO -> PNOZ (non-safety)",
                        "price_eur": 40, "assumed": True})
for p in n["profiles"]:
    for k in ("TRACER_DRIVE", "TRACER_CHG_IN"):
        p["p_avg"].pop(k, None)
ch = n["charging"]
ch["tracer_charge_w"] = 0
ch["charge_tracer_when_docked"] = False
ch["note"] = "combined station: MiR charging station (MiR battery) + our IC1200 on the RoboPad (our pack); MiR VL-marker docking +/-3 mm is inside the RoboPad +/-5 mm"

# --- safety functions on the MiR250
n["safety"]["functions"] = [
    {"id": "SF1", "desc": "E-stop -> SS1-t -> arm power removed by K1+K2", "plr": "d", "cat": 3,
     "chain": base["safety"]["functions"][0]["chain"]},
    {"id": "SF2", "desc": "MiR protective field violated -> arms SS1-t (needs a SAFE protective-stop output from MiR)", "plr": "d", "cat": 3,
     "chain": [{"name": "MiR250 safety system: protective-stop state as dual-channel safe output (availability NOT documented on the spec page)", "pfhd": None},
               {"name": "PNOZ m B0", "pfhd": 3.0e-9, "assumed": True},
               {"name": "K1+K2 + EDM", "pfhd": 1.0e-7, "assumed": True}]},
    {"id": "SF3", "desc": "Giorgio E-stop -> MiR250 auxiliary E-stop input -> base stop", "plr": "d", "cat": 3,
     "chain": [{"name": "E-stop 2NC", "pfhd": 1.0e-7, "assumed": True},
               {"name": "PNOZ m B0 + EF 4DI4DOR relay output", "pfhd": 1.3e-8, "assumed": True},
               {"name": "MiR250 auxiliary E-stop input + MiR safety system (ISO 13849-1 design claimed, PFHd placeholder 2e-7 for PL d)", "pfhd": 2.0e-7,
                "assumed": True, "source": "mir250"}]},
]
(HERE / "netlist_mir250.yaml").write_text(
    "# GENERATED by variants.py from netlist.yaml - do not edit by hand\n" + yaml.safe_dump(n, sort_keys=False, allow_unicode=True, width=160))
r = subprocess.run([sys.executable, str(HERE / "calc.py"), str(HERE / "netlist_mir250.yaml"), str(HERE / "CHECKS_MIR250.md")],
                   capture_output=True, text=True)
print(r.stdout)
